### ISSUE TITLE
Calculator crashes when file info is opened

### ISSUE THREAD

**Issue by Ocean-OS** [RoccoLoxPrograms/CEaShell#3]
I recently installed CEaShell, and when I attempt to view file info, the window that would show file info shows up, and then the calculator crashes and clears the RAM. I am running TI-OS version 54.0.0034.

**Comment by TIny-Hacker** [comment]
Do you have any more information about the file you're trying to view info on? I'm assuming you're using the latest release of CEaShell.

**Comment by Ocean-OS** [comment]
The error seems to happen on any file, archived or not, in any language.

**Comment by TIny-Hacker** [comment]
Sorry, but currently I'm unable to reproduce the issue. Would you be able to provide me the CEaShell version on your calculator and a list of files installed as well?
