### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by njphill0119** [RoccoLoxPrograms/CEaShell#6]
When I build with CE C Toolchain on Windows, I can use `make gfx` just fine, but when I run `make` it gives me this error:
~~~
'process_begin: CreateProcess(NULL, dirname C:/Users/mttph/Downloads/CEaShell/app_tools/makefile, ...) failed.
make: *** No rule to make target `obj/src/custom.c.bc', needed by `obj/lto.bc'.  Stop.'
~~~
Does anyone know if i've done anything wrong, or is there something wrong with the package?

**Comment by TIny-Hacker** [comment]
That's been an issue some people have had building on Windows. While I've never experienced the issue myself, @RoccoLoxPrograms and others found the best solution is to use WSL to build CEaShell.
