### ISSUE TITLE
Stuck in dark mode

### ISSUE THREAD

**Issue by FardUser** [RoccoLoxPrograms/CEaShell#8]
My TI-84 Plus CE is french :( so the buttons are a bit different. When I Press on+ln nothing happens.
Can you help me or give me a part of the source code that i can modify to change the button?

**Comment by RoccoLoxPrograms** [comment]
As long as you have the latest version of CEaShell installed, [on]+[ln] should take you out of dark mode just fine. If for some reason that doesn't work then turning the calculator off and back on will restore it to normal.
